Description: >
  Prometheus Server for Monitoring

Parameters:
  WorkflowID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: PrometheusSG-UdaPeople
      GroupDescription: Allow ports 22, 9090, 9093, 9100 and 3000.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9090
          ToPort: 9090
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9093
          ToPort: 9093
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9100
          ToPort: 9100
          CidrIp: 0.0.0.0/0
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: prometheus
      ImageId: ami-06878d265978313ca
      Tags:
        - Key: Name
          Value: PrometheusServer-UdaPeople
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo apt-get update
            sudo apt-get upgrade
            sudo useradd --no-create-home node_exporter
            wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
            tar xzf node_exporter-1.0.1.linux-amd64.tar.gz
            sudo cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
            rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64
            sudo bash -c 'echo "[Unit]
            Description=Prometheus Node Exporter Service
            After=network.target

            [Service]
            User=node_exporter
            Group=node_exporter
            Type=simple
            ExecStart=/usr/local/bin/node_exporter

            [Install]
            WantedBy=multi-user.target" > /etc/systemd/system/node-exporter.service'
            sudo systemctl daemon-reload
            sudo systemctl enable node-exporter
            sudo systemctl start node-exporter
            sudo useradd --no-create-home prometheus
            sudo mkdir /etc/prometheus
            sudo mkdir /var/lib/prometheus
            wget https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
            tar xvfz prometheus-2.19.0.linux-amd64.tar.gz
            sudo cp prometheus-2.19.0.linux-amd64/prometheus /usr/local/bin
            sudo cp prometheus-2.19.0.linux-amd64/promtool /usr/local/bin/
            sudo cp -r prometheus-2.19.0.linux-amd64/consoles /etc/prometheus
            sudo cp -r prometheus-2.19.0.linux-amd64/console_libraries /etc/prometheus
            sudo cp prometheus-2.19.0.linux-amd64/promtool /usr/local/bin/
            rm -rf prometheus-2.19.0.linux-amd64.tar.gz prometheus-2.19.0.linux-amd64
            sudo bash -c 'echo "global:
            scrape_interval: 15s
            evaluation_interval: 15s
            external_labels:
              monitor: 'Prometheus'

            scrape_configs:
              - job_name: 'prometheus'
                scrape_interval: 1s
                static_configs:
                  - targets: ['localhost:9090']
              - job_name: 'udapeople'
                scrape_interval: 1s
                static_configs:
                  - targets: ['localhost:9090']" > /etc/prometheus/prometheus.yml'
            sudo bash -c 'echo "[Unit]
            Description=Prometheus
            Wants=network-online.target
            After=network-online.target

            [Service]
            User=prometheus
            Group=prometheus
            Type=simple
            ExecStart=/usr/local/bin/prometheus \
                --config.file /etc/prometheus/prometheus.yml \
                --storage.tsdb.path /var/lib/prometheus/ \
                --web.console.templates=/etc/prometheus/consoles \
                --web.console.libraries=/etc/prometheus/console_libraries

            [Install]
            WantedBy=multi-user.target" > /etc/systemd/system/prometheus.service'
            sudo chown prometheus:prometheus /etc/prometheus
            sudo chown prometheus:prometheus /usr/local/bin/prometheus
            sudo chown prometheus:prometheus /usr/local/bin/promtool
            sudo chown -R prometheus:prometheus /etc/prometheus/consoles
            sudo chown -R prometheus:prometheus /etc/prometheus/console_libraries
            sudo chown -R prometheus:prometheus /var/lib/prometheus
            sudo systemctl daemon-reload
            sudo systemctl enable prometheus
            sudo systemctl start prometheus
            sudo systemctl start node-exporter
            wget https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
            tar xvfz alertmanager-0.21.0.linux-amd64.tar.gz
            sudo cp alertmanager-0.21.0.linux-amd64/alertmanager /usr/local/bin
            sudo cp alertmanager-0.21.0.linux-amd64/amtool /usr/local/bin/
            sudo mkdir /var/lib/alertmanager
            rm -rf alertmanager*
            sudo bash -c 'echo "[Unit]
            Description=Alert Manager
            Wants=network-online.target
            After=network-online.target

            [Service]
            Type=simple
            User=prometheus
            Group=prometheus
            ExecStart=/usr/local/bin/alertmanager \
              --config.file=/etc/prometheus/alertmanager.yml \
              --storage.path=/var/lib/alertmanager

            Restart=always

            [Install]
            WantedBy=multi-user.target" > /etc/systemd/system/alertmanager.service'
            sudo systemctl daemon-reload
            sudo systemctl enable alertmanager
            sudo systemctl start alertmanager
            sudo apt-get install -y adduser libfontconfig
            wget https://dl.grafana.com/oss/release/grafana_9.3.2_amd64.deb
            sudo dpkg -i grafana_9.3.2_amd64.deb
            sudo systemctl daemon-reload && sudo systemctl enable grafana-server && sudo systemctl start grafana-server