version: 2.1

commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy Ennvironment
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name YOURSTACKNAMEHERE-${CIRCLE_WORKFLOW_ID:0:7}
            exit 1
  revert_migrations:
    steps:
      - run:
          name: Revert Migrations
          when:
          command: |
            

jobs:

worflows: