version: 2.1

commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy Ennvironment
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name YOURSTACKNAMEHERE-${CIRCLE_WORKFLOW_ID:0:7}
            exit 1

jobs:
  build_frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build Frontend
          command: |
            cd frontend
            npm install
            npm run build
            exit 1
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
  build_backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Build Backend
          command: |
            cd backend
            npm install
            npm run build
            exit 1
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

workflows:
  app_deploy_workflow:
    jobs:
      - build_frontend
      - build_backend